Repository pinellolab/DNA-Diffusion, pull requests merged in 2023-10, with the labels that each got.

#222 motif composition metric notebook conversion
  src/dnadiffusion/metrics/motif_composition.py
  src/dnadiffusion/utils/data_util.py
  tests/test_data/data_util/motif_composition_helper_data.txt
  tests/test_data/metrics/motif_composition.txt
  tests/test_data/metrics/test_jaspar2020.pfm
  tests/test_data_util.py
  tests/test_motif_composition.py
Labels: enhancement, metrics

#228 update to torch `2.1.0`
  .github/mergify.yml
  .github/workflows/docker.yml
  dockerfiles/Dockerfile
  environments/conda/environment.yml
Labels: ci, build, dependencies

#229 fix: bump dev version `0.0.0.dev1`
  src/dnadiffusion/__about__.py
Labels: build

#230 refactor: separate pypi and conda containers
  .github/workflows/docker.yml
  dockerfiles/Dockerfile
  dockerfiles/Dockerfile.conda
Labels: ci, build

#236 fix cross_attention, removed unused_parameters flag
  src/dnadiffusion/models/unet.py
  train.py
Labels: enhancement, breaking

#247 replace black formatter with ruff
  notebooks/dnadiffusion.py
  notebooks/experiments/conditional_diffusion/full_script_version_from_accelerate_notebook/dnadiffusion.py
  pyproject.toml
  src/dnadiffusion/data/dataloader.py
  src/dnadiffusion/data/preprocessing.py
  src/dnadiffusion/metrics/motif_composition.py
  src/dnadiffusion/models/layers.py
  src/dnadiffusion/models/unet.py
  src/dnadiffusion/utils/data_util.py
  src/dnadiffusion/utils/sample_util.py
  src/dnadiffusion/utils/train_util.py
Labels: enhancement, build
