Repository pinellolab/DNA-Diffusion, pull requests merged in 2023-09, with the labels that each got.

#162 fix num samples outputted equal to user input
  src/dnadiffusion/utils/sample_util.py
Labels: bug

#167 feat: add renovate config
  .github/renovate.json
Labels: dependencies

#181 pin package versions
  pyproject.toml
Labels: dependencies

#184 fix: apply "dependencies" label to renovate PRs
  .github/renovate.json
Labels: dependencies

#190 feat: automate queue for merge
  .github/mergify.yml
Labels: ci

#192 Add heatmap generation functionality for cell specific synthetic sequences
  sample.py
  src/dnadiffusion/metrics/metrics.py
  src/dnadiffusion/utils/sample_util.py
  tests/test_sample_util.py
Labels: enhancement, metrics

#195 Fixes cell specific sample generation
  .gitignore
  checkpoints/.gitkeep
  notebooks/experiments/conditional_diffusion/full_script_version_from_accelerate_notebook/dnadiffusion.py
  sample.py
  src/dnadiffusion/metrics/metrics.py
  src/dnadiffusion/utils/sample_util.py
  src/dnadiffusion/utils/train_util.py
  tests/test_metrics.py
  tests/test_utils.py
  train.py
Labels: enhancement, metrics

#199 pin memory-efficient-attention-pytorch to final release version
  pyproject.toml
Labels: dependencies

#200 pin to memory-efficient-attention-pytorch to 0.1.2
  pyproject.toml
Labels: dependencies

#202 fix: pin all package versions
  pyproject.toml
Labels: dependencies

#205 fix compare_motif_list location call in motif data frame
  src/dnadiffusion/metrics/metrics.py
  tests/test_metrics.py
Labels: metrics

#207 Data preprocessing scripts for sequence validation dataset
  pyproject.toml
  src/dnadiffusion/data/validation_preprocessing.py
  src/dnadiffusion/utils/data_util.py
Labels: enhancement, metrics

#211 tests for data_util.py and validate_preprocessing.py
  src/dnadiffusion/data/validation_preprocessing.py
  src/dnadiffusion/utils/data_util.py
  tests/test_data/data_util/GENERATED_GM12878.txt
  tests/test_data/data_util/GENERATED_HEPG2.txt
  tests/test_data/data_util/GENERATED_HESCT0.txt
  tests/test_data/data_util/GENERATED_K562.txt
  tests/test_data/data_util/PROMOTERS.txt
  tests/test_data/data_util/RANDOM_GENOME_REGIONS.txt
  tests/test_data/data_util/seq_extract_data.txt
  tests/test_data/data_util/test_GM12878.txt
  tests/test_data/data_util/test_HepG2.txt
  tests/test_data/data_util/test_K562.txt
  tests/test_data/data_util/test_hESCT0.txt
  tests/test_data/data_util/training_GM12878.txt
  tests/test_data/data_util/training_HepG2.txt
  tests/test_data/data_util/training_K562.txt
  tests/test_data/data_util/training_hESCT0.txt
  tests/test_data/data_util/validation_GM12878.txt
  tests/test_data/data_util/validation_HepG2.txt
  tests/test_data/data_util/validation_K562.txt
  tests/test_data/data_util/validation_hESCT0.txt
  tests/test_data/validation_preprocessing/df_train.txt
  tests/test_data_util.py
  tests/test_validation_preprocessing.py
Labels: enhancement
