Repository pinellolab/DNA-Diffusion, pull requests merged in 2023-03, with the labels that each got.

#78 add contributor covenant code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation

#82 add actions/stale for issues and prs
  .github/workflows/inactive-issues-prs.yml
Labels: documentation, ci

#84 Adding subscripts created from original single script
  dna-diffusion/.DS_Store
  dna-diffusion/data/dataloader.py
  dna-diffusion/metrics/metrics.py
  dna-diffusion/models/diffusion.py
  dna-diffusion/models/networks.py
  dna-diffusion/requirements.yml
  dna-diffusion/sample.py
  dna-diffusion/trainer.py
  dna-diffusion/utils/ema.py
  dna-diffusion/utils/scheduler.py
  dna-diffusion/utils/utils.py
Labels: enhancement, refactoring

#92 merge codebase changes on main into default
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci.yml
  .idea/workspace.xml
  pyproject.toml
  requirements.txt
  src/README.md
  src/__pycache__/config.cpython-39.pyc
  src/config.py
  src/configs/callbacks/default.yaml
  src/configs/data/sequence.yaml
  src/configs/data/vanilla_sequences.yaml
  src/configs/logger/wandb.yaml
  src/configs/main.yaml
  src/configs/model/dnaddpmdiffusion.yaml
  src/configs/model/dnadiffusion.yaml
  src/configs/model/lr_scheduler/MultiStepLR.yaml
  src/configs/model/optimizer/adam.yaml
  src/configs/model/unet/unet.yaml
  src/configs/model/unet/unet_conditional.yaml
  src/configs/paths/default.yaml
  src/configs/trainer/ddp.yaml
  src/configs/trainer/default.yaml
  src/data/__pycache__/sequence_datamodule.cpython-39.pyc
  src/data/sequence_dataloader.py
  src/data/sequence_datamodule.py
  src/main.py
  src/models/diffusion/__pycache__/ddpm.cpython-39.pyc
  src/models/diffusion/__pycache__/diffusion.cpython-39.pyc
  src/models/diffusion/ddpm.py
  src/models/diffusion/diffusion.py
  src/models/encoders/vqvae.py
  src/models/networks/__pycache__/unet_lucas.cpython-39.pyc
  src/models/networks/__pycache__/unet_lucas_cond.cpython-39.pyc
  src/models/networks/unet_lucas.py
  src/models/networks/unet_lucas_cond.py
  src/sample.py
  src/utils/__pycache__/ema.cpython-39.pyc
  src/utils/__pycache__/misc.cpython-39.pyc
  src/utils/__pycache__/network.cpython-39.pyc
  src/utils/__pycache__/schedules.cpython-39.pyc
  src/utils/ema.py
  src/utils/metrics.py
  src/utils/misc.py
  src/utils/network.py
  src/utils/schedules.py
  src/wandb/settings
  tests/__init__.py
  tests/data/test_sequence_dataloader.py
  tests/models/diffusion/test_ddim.py
  tests/models/diffusion/test_ddpm.py
  tests/models/encoders/test_vqvae.py
  tests/models/networks/test_unet_bitdiffusion.py
  tests/models/networks/test_unet_lucas.py
  tests/utils/test_ema.py
  tests/utils/test_misc.py
  tests/utils/test_network.py
  tests/utils/test_schedules.py
Labels: enhancement, refactoring

#99 Comment out config.py to resolve pre-commit parsing error
  .github/PULL_REQUEST_TEMPLATE.md
  .pre-commit-config.yaml
  dnadiffusion/trainer.py
  notebooks/experiments/conditional_diffusion/full_script_version_from_accelerate_notebook/dnadiffusion.py
  src/config.py
  src/configs/data/vanilla_sequences.yaml
  src/configs/model/dnaddpmdiffusion.yaml
  src/configs/model/dnadiffusion.yaml
  src/configs/model/lr_scheduler/MultiStepLR.yaml
  src/configs/model/optimizer/adam.yaml
  src/configs/model/unet/unet_conditional.yaml
  src/configs/trainer/ddp.yaml
  src/data/sequence_dataloader.py
  src/data/sequence_datamodule.py
  src/main.py
  src/models/diffusion/ddpm.py
  src/models/diffusion/diffusion.py
  src/models/networks/unet_lucas.py
  src/utils/ema.py
  src/utils/misc.py
  src/utils/network.py
  src/wandb/settings
Labels: bug, ci

#100 adding the kmer metrics
  dnadiffusion/metrics/metrics.py
Labels: metrics

#105 pytorch-lightning/hydra-zen integration
  .gitignore
  .pre-commit-config.yaml
  dnadiffusion/callbacks/ema.py
  dnadiffusion/callbacks/sampling.py
  dnadiffusion/configs.py
  dnadiffusion/data/dataloader.py
  dnadiffusion/metrics/metrics.py
  dnadiffusion/metrics/sampling_metrics.py
  dnadiffusion/metrics/validation_metrics.py
  dnadiffusion/models/diffusion.py
  dnadiffusion/models/modules.py
  dnadiffusion/models/training_modules.py
  dnadiffusion/models/unet.py
  dnadiffusion/sample.py
  dnadiffusion/utils/ema.py
  train.py
Labels: enhancement, codebase

#108 Removed validation metrics from sampling metrics
  dnadiffusion/metrics/sampling_metrics.py
Labels: codebase, refactoring

#119 add documentation
  .github/workflows/documentation.yml
  docs/index.md
  docs/reference/dnadiffusion.md
  mkdocs.yml
Labels: documentation

#121 add docker container
  .github/workflows/docker.yml
  dockerfiles/Dockerfile
Labels: build

#125 add release workflows
  .github/release-drafter.yml
  .github/workflows/release.yml
  .github/workflows/test-release.yml
  dockerfiles/Dockerfile
Labels: ci

#127 Changes all import lightning to import pytorch_lightning
  src/dnadiffusion/callbacks/ema.py
  src/dnadiffusion/callbacks/sampling.py
  src/dnadiffusion/configs.py
  src/dnadiffusion/data/dataloader.py
  src/dnadiffusion/models/training_modules.py
  train.py
Labels: bug

#129 make release depend on build and docker
  .github/workflows/docker.yml
  .github/workflows/release.yml
  .github/workflows/test-release.yml
  dockerfiles/Dockerfile
  src/dnadiffusion/configs.py
  src/dnadiffusion/data/dataloader.py
Labels: ci

#131 use smaller README image
  README.md
  docs/images/diff_first_lossy.gif
  docs/reference/dnadiffusion.md
Labels: documentation

#133 add example slurm submission
  environments/cluster/.env
  environments/cluster/README.md
  environments/cluster/create_conda.sh
  environments/cluster/dnadiffusion_run.sh
  environments/cluster/install_mambaforge.sh
  environments/cluster/slurm_interactive.sh
  environments/cluster/test_path.sh
Labels: enhancement
